package com.yimeng.seed.organ.model;

import java.util.Date;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgid
     *
     * @mbggenerated
     */
    private Long orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.platid
     *
     * @mbggenerated
     */
    private Integer platid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgname
     *
     * @mbggenerated
     */
    private String orgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgtype
     *
     * @mbggenerated
     */
    private String orgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.contact_name
     *
     * @mbggenerated
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.contact_phone
     *
     * @mbggenerated
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.areacode
     *
     * @mbggenerated
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.images
     *
     * @mbggenerated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgid
     *
     * @return the value of organization.orgid
     *
     * @mbggenerated
     */
    public Long getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgid
     *
     * @param orgid the value for organization.orgid
     *
     * @mbggenerated
     */
    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.platid
     *
     * @return the value of organization.platid
     *
     * @mbggenerated
     */
    public Integer getPlatid() {
        return platid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.platid
     *
     * @param platid the value for organization.platid
     *
     * @mbggenerated
     */
    public void setPlatid(Integer platid) {
        this.platid = platid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgname
     *
     * @return the value of organization.orgname
     *
     * @mbggenerated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgname
     *
     * @param orgname the value for organization.orgname
     *
     * @mbggenerated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgtype
     *
     * @return the value of organization.orgtype
     *
     * @mbggenerated
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgtype
     *
     * @param orgtype the value for organization.orgtype
     *
     * @mbggenerated
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype == null ? null : orgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.contact_name
     *
     * @return the value of organization.contact_name
     *
     * @mbggenerated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.contact_name
     *
     * @param contactName the value for organization.contact_name
     *
     * @mbggenerated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.contact_phone
     *
     * @return the value of organization.contact_phone
     *
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.contact_phone
     *
     * @param contactPhone the value for organization.contact_phone
     *
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.areacode
     *
     * @return the value of organization.areacode
     *
     * @mbggenerated
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.areacode
     *
     * @param areacode the value for organization.areacode
     *
     * @mbggenerated
     */
    public void setAreacode(Integer areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.longitude
     *
     * @return the value of organization.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.longitude
     *
     * @param longitude the value for organization.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.latitude
     *
     * @return the value of organization.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.latitude
     *
     * @param latitude the value for organization.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.logo
     *
     * @return the value of organization.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.logo
     *
     * @param logo the value for organization.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.images
     *
     * @return the value of organization.images
     *
     * @mbggenerated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.images
     *
     * @param images the value for organization.images
     *
     * @mbggenerated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.introduce
     *
     * @return the value of organization.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.introduce
     *
     * @param introduce the value for organization.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.create_time
     *
     * @return the value of organization.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.create_time
     *
     * @param createTime the value for organization.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}